server:
  port: 8080

spring:
  application:
    name: weibo
  profiles:
    active: dev
  # 数据库配置
  datasource:
    driver-class-name: ${weibo.datasource.driver-class-name}
    url: jdbc:mysql://${weibo.datasource.host}:${weibo.datasource.port}/${weibo.datasource.database}
    username: ${weibo.datasource.userName}
    password: ${weibo.datasource.password}

  # redis配置
  data:
    redis:
      host: ${weibo.redis.host}
      port: ${weibo.redis.port}
      password: ${weibo.redis.password}
      database: ${weibo.redis.database}
      client-type: lettuce
      timeout: 3000ms
      # 哨兵模式
      sentinel:
        master: mymaster                   # 哨兵里配置的 master 名（需与 redis-sentinel.conf 中一致）
        nodes: ${weibo.redis.sentinel.nodes}  # 3 个哨兵，逗号分隔，192.168.80.128:27000,192.168.80.129:27001,192.168.80.130:27002
        password: ${weibo.redis.sentinel.password} 
      lettuce:
        pool:
          max-active: 10
          max-wait: 3000ms
          max-idle: 8
          min-idle: 2

  # 邮箱配置
  mail:
    host: smtp.qq.com
    port: 465                # SSL加密端口
    username: ${weibo.email.username}
    password: ${weibo.email.password}
    properties:
      mail:
        smtp:
          auth: true         # 开启认证
          ssl:
            enable: true     # 开启SSL加密
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
  # 配置文件,导入开发环境的配置文件
  config:
    import:
      classpath: application-dev.yml
  # servlet配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    sql: debug
    io.lettuce.core: debug
# alioss配置
alioss:
  endpoint: ${weibo.endpoint}
  access-key-id: ${weibo.access-key-id}
  access-key-secret: ${weibo.access-key-secret}
  bucket-name: ${weibo.bucket-name}
# jwt配置
jwt:
  # 设置jwt签名加密时使用的秘钥
  secret-key: huawei_secret_for_spring_security_generation_as_jwt_to_use
  # 设置jwt过期时间
  ttlMillis: 864000000
  # 设置前端传递过来的令牌名称
  token-name: token

