weibo:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: use_big_event
    userName: root
    password: ${MYSQL_PASSWORD}
  redis:
    host: 192.168.80.128
    port: 6379
    password: ${MYSQL_PASSWORD}
    database: 0
    sentinel:
      nodes: 192.168.80.128:27000,192.168.80.129:27001,192.168.80.130:27002
      password: ${MYSQL_PASSWORD}
  #文件上传
  email:
    username: 2426912619@qq.com
    password: ${PATH_tengxun_qq_email}

#文件上传
  # 阿里云OSS 地域节点（服务访问地址）
  endpoint: https://oss-cn-beijing.aliyuncs.com
  # 阿里云身份凭证ID（相当于“账号”）
  access-key-id: ${PATH_alibaba_oss_id}
  # 阿里云身份凭证密钥（相当于“密码”）
  access-key-secret: ${PATH_alibaba_oss_secret}
  # 阿里云OSS 存储空间名称（相当于“网盘文件夹”）
  bucket-name: java-web-ai-wangnian
